name: apptutortrack
description: MVP Flutter offline-first para seguimiento académico y emocional
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  crypto: ^3.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.0.4
  fl_chart: ^0.68.0
  pdf: ^3.11.1
  excel: ^2.1.0
  image_picker: ^1.0.7
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/simulated_data.csv
    - assets/images/emojis/
